---
- name: Configure the declared trunk links
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{ item.name }}"
        mode: trunk
        trunk:
          native_vlan: "{{ native_vlan }}"
          allowed_vlans: "{{ item.allowed_vlans }}"
    state: merged
  loop: "{{ trunk_interfaces | default([]) }}"
