---
local_vlans: [40, 99, 100]
management_ip: 10.99.99.24
management_mask: 255.255.255.0
management_gateway: 10.99.99.1
trunk_interfaces:
  - { name: GigabitEthernet0/0, allowed_vlans: "40,99,100" }
access_ports:
  - { interface: GigabitEthernet0/1, vlan: 40 }
  - { interface: GigabitEthernet0/2, vlan: 40 }
  - { interface: GigabitEthernet0/3, vlan: 40 }
