---
- name: Ensure the VLANs required by this switch exist
  cisco.ios.ios_vlans:
    config:
      - vlan_id: "{{ item }}"
        name: "{{ campus_vlan_names[item] }}"
    state: merged
  loop: "{{ local_vlans }}"
