---
- name: Use Rapid-PVST
  cisco.ios.ios_config:
    lines:
      - spanning-tree mode rapid-pvst

- name: Enable PortFast only on end-host ports
  cisco.ios.ios_config:
    parents: "interface {{ item.interface }}"
    lines:
      - spanning-tree portfast
  loop: "{{ access_ports | default([]) }}"
