---
all:
  children:
    switches:
      children:
        distribution:
          hosts:
            SW-D-DEIE:
              ansible_host: 10.99.10.11
            SW-D-DCEE:
              ansible_host: 10.99.20.12
            SW-D-DMME:
              ansible_host: 10.99.30.13
        access:
          hosts:
            SW-A-DEIE:
              ansible_host: 10.99.10.21
            SW-A-DCEE:
              ansible_host: 10.99.20.22
            SW-A-DMME:
              ansible_host: 10.99.30.23
            SW-A-DIS:
              ansible_host: 10.99.99.24
        core_switch:
          hosts:
            SW-CORE:
              ansible_host: 10.99.99.1