---
lab:
  children:
    switches:
      hosts:
        
    vars:
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: ios
      ansible_user: 
      ansible_password: 
      ansible_connection: ssh





