---
all:
  children:
    switches:
      hosts:
        SW-CORE:
          ansible_host: 10.99.99.1
          ansible_user: admin
          ansible_password: admin
          ansible_become_password: admin
        SW-D-DEIE:
          ansible_host: 10.99.99.10
          ansible_user: admin
          ansible_password: cisco123
          ansible_become_password: cisco123
        SW-A-DEIE:
          ansible_host: 10.99.99.15
          ansible_user: admin
          ansible_password: cisco123
          ansible_become_password: cisco123
        SW-D-DCEE:
          ansible_host: 10.99.99.20
          ansible_user: admin
          ansible_password: admin
          ansible_become_password: admin
        SW-A-DCEE:
          ansible_host: 10.99.99.25
          ansible_user: admin
          ansible_password: admin
          ansible_become_password: admin
        SW-D-DMME:
          ansible_host: 10.99.99.30
          ansible_user: admin
          ansible_password: admin
          ansible_become_password: admin
        SW-A-DMME:
          ansible_host: 10.99.99.35
          ansible_user: admin
          ansible_password: admin
          ansible_become_password: admin
        SW-A-DIS:
          ansible_host: 10.99.99.45
          ansible_user: admin
          ansible_password: admin
          ansible_become_password: admin