---
- name: Configure distribution switches
  hosts: distribution
  gather_facts: false
  roles:
    - vlans
    - management
    - distribution_routing
    - stp
    - trunking

- name: Configure access switches
  hosts: access
  gather_facts: false
  roles:
    - vlans
    - management
    - stp
    - trunking
    - access_ports
